"milestones":
  - "title": "2.1.0"
    "description": "Minor release – targeting 2.1.x branch (semantic version: 2.1.0)"
    "state": "open"
  - "title": "2.0.1"
    "description": "Patch release – targeting 2.0.x branch (semantic version: 2.0.1)"
    "state": "open"
  - "title": "3.0.0"
    "description": "Major release – targeting 3.0.x branch (semantic version: 3.0.0)"
    "state": "open"
  - "title": "3.1.0"
    "description": "Minor release – targeting 3.1.x branch (semantic version: 3.1.0)"
    "state": "open"
  - "title": "4.0.0"
    "description": "Major release – targeting 4.0.x branch (semantic version: 4.0.0)"
    "state": "open"
  - "title": "2.0.0"
    "description": "Major release – targeting 2.0.x branch (semantic version: 2.0.0)"
    "state": "closed"
"repository":
  "name": "collection"
  "description": "Provides a Collection implementation for PHP"
  "topics": "collection, ghostwriter"
  "homepage": "https://github.com/ghostwriter/collection"
  "default_branch": "2.0.x"
  "allow_auto_merge": true
  "allow_forking": true
  "allow_merge_commit": true
  "allow_rebase_merge": true
  "allow_squash_merge": true
  "allow_update_branch": true
  "delete_branch_on_merge": true
  "enable_automated_security_fixes": true
  "enable_vulnerability_alerts": true
  "has_downloads": true
  "has_issues": true
  "has_projects": false
  "has_wiki": false
  "security_and_analysis":
    "advanced_security":
      "status": "enabled"
    "code_security":
      "status": "enabled"
    "secret_scanning":
      "status": "enabled"
    "secret_scanning_ai_detection":
      "status": "enabled"
    "secret_scanning_non_provider_patterns":
      "status": "enabled"
    "secret_scanning_push_protection":
      "status": "enabled"
  "web_commit_signoff_required": true
